import logging
import os
from typing import List, Literal, Optional

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
import google.generativeai as genai


load_dotenv()


class ChatMessage(BaseModel):
    role: Literal["user", "assistant", "system"] = Field(
        ..., description="Originator of the message."
    )
    content: str = Field(..., description="Natural language message content.")


class ChatRequest(BaseModel):
    messages: List[ChatMessage] = Field(
        ..., description="Full conversation history in chronological order."
    )


class ChatResponse(BaseModel):
    reply: str = Field(..., description="Assistant response generated by Gemini.")


def configure_model() -> genai.GenerativeModel:
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise RuntimeError(
            "GEMINI_API_KEY not configured. Set it in the environment or .env file."
        )

    genai.configure(api_key=api_key)
    model_name = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")

    return genai.GenerativeModel(
        model_name=model_name,
        generation_config={
            "temperature": float(os.getenv("GEMINI_TEMPERATURE", "0.4")),
            "top_p": float(os.getenv("GEMINI_TOP_P", "0.95")),
        },
    )


logger = logging.getLogger("medibots.chatbackend")
logging.basicConfig(level=logging.INFO)

app = FastAPI(title="MediBots Chat API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=os.getenv("FRONTEND_ORIGIN", "http://localhost:5173").split(","),
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

try:
    chat_model: Optional[genai.GenerativeModel] = configure_model()
except RuntimeError as config_err:
    chat_model = None
    logger.error(str(config_err))


@app.get("/health")
def health_check() -> dict:
    return {"status": "ok"}


@app.post("/api/chat", response_model=ChatResponse)
def chat(request: ChatRequest) -> ChatResponse:
    if chat_model is None:
        raise HTTPException(
            status_code=500,
            detail="Gemini model is not configured. Check server logs for details.",
        )

    if not request.messages:
        raise HTTPException(status_code=400, detail="No messages provided.")

    system_instruction: Optional[str] = None
    chat_history: List[dict] = []

    for message in request.messages:
        if message.role == "system":
            system_instruction = message.content
            continue

        role = "user" if message.role == "user" else "model"
        chat_history.append({"role": role, "parts": [{"text": message.content}]})

    if not chat_history:
        raise HTTPException(
            status_code=400,
            detail="Conversation must include at least one non-system message.",
        )

    if chat_history[-1]["role"] != "user":
        raise HTTPException(
            status_code=400,
            detail="Last conversation message must come from the user.",
        )

    last_message = chat_history.pop()

    try:
        start_kwargs = {"history": chat_history}
        try:
            if system_instruction:
                session = chat_model.start_chat(
                    **start_kwargs, system_instruction=system_instruction
                )
            else:
                session = chat_model.start_chat(**start_kwargs)
        except TypeError as type_err:
            if not system_instruction or "system_instruction" not in str(type_err):
                raise

            augmented_history = [
                {"role": "user", "parts": [{"text": system_instruction}]},
                *chat_history,
            ]
            session = chat_model.start_chat(history=augmented_history)

        response = session.send_message(last_message["parts"][0]["text"])
    except Exception as exc:  # pragma: no cover - defensive logging
        raise HTTPException(status_code=500, detail=str(exc)) from exc

    reply = (response.text or "").strip()
    if not reply:
        raise HTTPException(
            status_code=500,
            detail="Gemini returned an empty response.",
        )

    return ChatResponse(reply=reply)
